### ISSUE TITLE
CSS box-sizing

### ISSUE THREAD

**Issue by man4red** [zendframework/ZendDeveloperTools#145]
I know, that this is not an error at all, but:

If I use bootstratp CSS, for example - there present this style definition:

``` css
/* bootstrap.css #259 */
* {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
```

So with this borders I've got some irritating behavior when mouseover on some ZendTools button and popup content showed over button and I'm trying move my mouse to this content - it disappears!

Because of borders adds some extra space and mouseover event brokes.
Works if I move mouse over green arrow :)

I know, that this is behavior of bootstrap.css, but if u will add this:

``` css
#zend-developer-toolbar {
...
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
...
}
```

then problem will be fixed on all possible CSS frameworks, I think.

Sorry for my english.
Thx
